# Generated by Django 5.1.6 on 2025-06-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expression', models.TextField(help_text='Write formula like a + b * c - d / e')),
                ('variables', models.JSONField(help_text='List of variables like ["a", "b", "c", "d", "e"]')),
            ],
        ),
    ]
